"""
Configuration file for hpp vos method
"""
# constants for color_soft_segs.py
COLOR_SOFT_SEG_DIM_H = 100
COLOR_SOFT_SEG_DIM_S = 25
COLOR_SOFT_SEG_DIM_V = 10

# constants for patch_analysis.py
PATCH_SOFT_SEG_DIM_H = 15
PATCH_SOFT_SEG_DIM_S = 11
PATCH_SOFT_SEG_DIM_V = 7

PATCH_SOFT_SEG_HALF_PATCH_SIZE = 8

PATCH_SOFT_SEG_TRAIN_SAMPLES_STEP_X = 8
PATCH_SOFT_SEG_TRAIN_SAMPLES_STEP_Y = 8

PATCH_SOFT_SEG_TEST_SAMPLES_STEP_X = 1
PATCH_SOFT_SEG_TEST_SAMPLES_STEP_Y = 1

PATCH_SOFT_SEG_LAMBDA = 20

PATCH_SOFT_SEG_HYSTHRESH_T1 = 0.8
PATCH_SOFT_SEG_HYSTHRESH_T2 = 0.5

PATCH_SOFT_SEG_N_FEATURES = 250

# constants for video PCA
VIDEO_PCA_SIGMA_BLUR = 5
VIDEO_PCA_N_DIRECTIONS = 3
VIDEO_PCA_SOFT_SEGS_N_DIRECTIONS = 8
